---
name: "autorelease"

on:
  push:
    branches: ["master", "main"]

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Fetch repository"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Fetch SuM"
        run: curl https://www.mg-werl.de/sum/SuMWin.zip --output sum.zip && unzip sum.zip -d SuM && find SuM/ -name \*.jar -exec cp {} SuM \;

      - name: "Delete bloat"
        run: rm SuM/SuMAkzeptor.jar SuM/SuMGenerator.jar SuM/SuMTransduktor.jar

      - name: "Compile"
        run: javac -cp SuM/\* `find src/ -name \*.java`

      - name: "Decompress SuM library"
        run: unzip -o -d . 'SuM/*.jar'

      - name: "Move all class files to a separate folder"
        run: mkdir sum-src && find sum/ -name '*.class' -exec cp --parents \{\} sum-src \;

      - name: "Create jar"
        run: rm -rf sum && mv sum-src/* . && mv `find src/ -name \*.class` . && jar cf Panit.jar *.class sum/ icon.png && chmod +x Panit.jar

      - name: "Update manifest"
        run: jar -uvfe Panit.jar Main

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Panit
          path: Panit.jar

      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build for commit ${{ steps.hash.outputs.sha_short }}"
          files: Panit.jar

