---
name: "autoformat"

on:
  push:
    branches: ["master", "main"]

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Fetch repository"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: "Autoformat"
        run: find src/ -name '*.java' -exec clang-format -i -style=file {} \;

      - name: "Set up git"
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: "Push"
        run: echo `git add -u && git commit -m "Autoformat" && git push`

